name: Build Android APK

on:
  push:
    branches: [main]  # Cambia 'main' por el nombre de tu rama si es diferente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install briefcase

    - name: Create APK with Briefcase
      run: |
        mkdir CombinatoriosApp
        cp Combinatorios_AIO_V9.py CombinatoriosApp/main.py
        echo '[tool.briefcase]' > pyproject.toml
        echo 'project_name = "CombinatoriosApp"' >> pyproject.toml
        echo 'version = "1.0.0"' >> pyproject.toml
        echo 'bundle = "com.example"' >> pyproject.toml
        echo 'app_name = "CombinatoriosApp"' >> pyproject.toml
        echo 'formal_name = "CombinatoriosApp"' >> pyproject.toml
        echo 'description = "Aplicación de combinatorias"' >> pyproject.toml
        echo 'author = "Tu Nombre"' >> pyproject.toml
        echo 'author_email = "tuemail@example.com"' >> pyproject.toml
        echo 'license = "MIT"' >> pyproject.toml
        echo '[tool.briefcase.app.CombinatoriosApp]' >> pyproject.toml
        echo 'sources = ["CombinatoriosApp"]' >> pyproject.toml
        briefcase create android
        briefcase build android

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CombinatoriosApp-apk
        path: dist/CombinatoriosApp/*.apk
